### PR TITLE
Mergify: configuration update

### PR DESCRIPTION
**Pull request by jguiditta**
This change has been made by @jguiditta from https://mergify.io config editor.

### CODE REVIEW

**Comment by jguiditta** [comment]
This can be verified by looking at 
https://dashboard.mergify.io/github/release-depot/config-editor?repositoryName=tag-utils&pullRequestNumber=12
You simply need there to copy in the changes from this patch, and then click 'check my configuration'. Everything but the 'approved by' bit should be checked, whereas the test results will NOT be checked against the current version of our mergify.yaml

**Comment by jguiditta** [comment]
BTW, PR#12 is there specifically for verifying this change, and I will close once this is in.

**Review by jpichon — APPROVED** [review]
LGTM!

**Review by fuzzball81 — APPROVED** [review]
LGTM

**Pull request merged**
